AWSTemplateFormatVersion: 2010-09-09
Resources:
  dynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - 
          AttributeName: id
          KeyType: HASH

Outputs:
  TableName:
    Description: "DynamoDB CF Stack"
    Value:  !Ref dynamodbTable
    Export:
      Name:  !Sub ${AWS::StackName}-ddb-table-name
      
